import Footer from "@/common/footer";
import Header from "@/common/header";
import "./globals.scss";

export const metadata = {
  title: "INTERO - EVOLUTION",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Biryani:wght@200;300;400;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
          <Header />
          <main>{children}</main>
          <Footer />
      </body>
    </html>
  );
}
